# Generated by Django 4.1.1 on 2022-09-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasks',
            new_name='task',
        ),
    ]
